%% Grouped conditions file, specifies which conditions belong together in
% the form:
% Grouped conditions, cond2/4 = transformed to cond1/3, form below
% {[cond1_rep1... cond1_repN], [cond2_rep1... cond2_repN]; 
% [cond3_rep1... cond3_repN], [cond4_rep1... cond4_repN]}
%
% This file is used to hopefully automate comparisons later on

%%
sym_conditions = ...
                       {[1,2];...   
                        [3,4];...   
                        [5,6];...   
                        [7,8];...   
                        [9,10]};

grouped_conditions{1}.name = 'Lateral Expansion (CW)';
grouped_conditions{1}.tf = [.75 1.5 3 5 8];
grouped_conditions{1}.dps = [12 24 48 80 128]*3.75;
grouped_conditions{1}.x_label = 'Speed';
grouped_conditions{1}.list = ...
                       {[1,2];...
                        [3,4];...
                        [5,6];...
                        [7,8];...
                        [9,10]};