% Grouped conditions file, specifies which conditions belong together in
% the form:
% Grouped conditions, cond2/4 = transformed to cond1/3, form below
% {[cond1_rep1... cond1_repN], [cond2_rep1... cond2_repN]; 
% [cond3_rep1... cond3_repN], [cond4_rep1... cond4_repN]}
%
% This file is used to automate comparisons later on
grouped_conditions = {  [1,2];... % 1
                        [2,6];... % 2
                        [3,6];... % 3
                        [4,6];... % 4
                        [5,6];... % 1
                        [6,6];... % 1
                        [7,6];... % 1
                        [8,6];... % 1
                        [9,6];... % 1
                        [10,6];... % 1
                        [11,6];... % 1
                        [12,6];... % 1
                        [13,6];... % 1
                        [14,6];... % 1
                        [15,6];... % 1
                        [16,6];... % 1
                        [17,6];... % 1
                        [18,6];... % 1
                        [19,6];... % 1                        
                        [20,8]};
                    
grouped_cond_params.temporal_freq = ...
                       {0.5;...
                        1.0;...         
                        2.0;...
                        3.0};
                    
grouped_cond_params.phase_delay = ...
                           {0;...
                            2.5;...
                            10;... 
                            20;... 
                            27.5;... 
                            37.5;... 
                            45;... 
                            55;... 
                            62.5;... 
                            ...
                            -10};...
                            
